import { Agent } from "./types";
import { AGENT_PROVIDER } from "./providers-config";

const withProvider = (agent: Omit<Agent, "provider">): Agent => ({
  ...agent,
  provider: AGENT_PROVIDER[agent.id] ?? "gemini",
});

export const DEFAULT_AGENTS: Agent[] = [
  withProvider({
    id: "planner",
    name: "PlannerAgent",
    role: "Decomposes missions into structured subtask graphs",
    skills: ["planning", "decomposition", "strategy", "coordination"],
    price: 0.04,
    reputation: 88,
    factuality: 0.88,
    usefulness: 0.92,
    collaboration: 0.90,
    latencyAvg: 1.2,
    status: "idle",
    alpha: 8,
    beta: 2,
    meanReward: 0.82,
    uncertainty: 0.09,
    runs: 12,
    wins: 9,
    losses: 2,
    elo: 1480,
    ucbScore: 0,
    graphTrust: 0.75,
    bayesianMean: 0.8,
  }),
  withProvider({
    id: "codex",
    name: "CodexAgent",
    role: "Builds product specs, positioning, and technical implementation plans",
    skills: ["product_design", "synthesis", "go_to_market", "positioning", "implementation", "architecture", "copywriting", "landing_page"],
    price: 0.07,
    reputation: 82,
    factuality: 0.85,
    usefulness: 0.90,
    collaboration: 0.82,
    latencyAvg: 1.8,
    status: "idle",
    alpha: 7,
    beta: 2,
    meanReward: 0.78,
    uncertainty: 0.10,
    runs: 10,
    wins: 8,
    losses: 1,
    elo: 1455,
    ucbScore: 0,
    graphTrust: 0.70,
    bayesianMean: 0.75,
  }),
  withProvider({
    id: "claude",
    name: "ClaudeAgent",
    role: "Critiques outputs, writes pitch narratives, and verifies factual claims",
    skills: ["critique", "strategy", "pitch", "narrative", "copywriting", "landing_page", "fact_checking", "source_verification", "risk_analysis", "critical_thinking"],
    price: 0.06,
    reputation: 91,
    factuality: 0.93,
    usefulness: 0.90,
    collaboration: 0.87,
    latencyAvg: 1.5,
    status: "idle",
    alpha: 9,
    beta: 2,
    meanReward: 0.88,
    uncertainty: 0.07,
    runs: 14,
    wins: 12,
    losses: 1,
    elo: 1510,
    ucbScore: 0,
    graphTrust: 0.82,
    bayesianMean: 0.82,
  }),
  withProvider({
    id: "gemini",
    name: "GeminiAgent",
    role: "Conducts market research, synthesizes data, and generates broad ideation outputs",
    skills: ["research", "market_analysis", "data_synthesis", "competitive_intel", "ideation", "synthesis", "go_to_market"],
    price: 0.05,
    reputation: 80,
    factuality: 0.78,
    usefulness: 0.83,
    collaboration: 0.75,
    latencyAvg: 1.2,
    status: "idle",
    alpha: 6,
    beta: 3,
    meanReward: 0.72,
    uncertainty: 0.13,
    runs: 10,
    wins: 7,
    losses: 2,
    elo: 1430,
    ucbScore: 0,
    graphTrust: 0.62,
    bayesianMean: 0.67,
  }),
  withProvider({
    id: "evaluator",
    name: "EvaluatorAgent",
    role: "Scores agent outputs on quality, factuality, and usefulness",
    skills: ["evaluation", "scoring", "quality_assurance", "feedback"],
    price: 0.03,
    reputation: 90,
    factuality: 0.93,
    usefulness: 0.90,
    collaboration: 0.88,
    latencyAvg: 1.0,
    status: "idle",
    alpha: 9,
    beta: 2,
    meanReward: 0.88,
    uncertainty: 0.07,
    runs: 18,
    wins: 16,
    losses: 1,
    elo: 1500,
    ucbScore: 0,
    graphTrust: 0.80,
    bayesianMean: 0.82,
  }),
  withProvider({
    id: "market_maker",
    name: "MarketMakerAgent",
    role: "Orchestrates auctions and selects optimal agent swarms",
    skills: ["routing", "optimization", "orchestration", "auction"],
    price: 0.02,
    reputation: 92,
    factuality: 0.90,
    usefulness: 0.94,
    collaboration: 0.92,
    latencyAvg: 0.8,
    status: "idle",
    alpha: 9,
    beta: 2,
    meanReward: 0.90,
    uncertainty: 0.07,
    runs: 20,
    wins: 18,
    losses: 1,
    elo: 1520,
    ucbScore: 0,
    graphTrust: 0.85,
    bayesianMean: 0.82,
  }),
  withProvider({
    id: "reputation",
    name: "ReputationAgent",
    role: "Updates agent reputation scores after each mission",
    skills: ["reputation", "memory", "scoring", "feedback"],
    price: 0.01,
    reputation: 89,
    factuality: 0.92,
    usefulness: 0.88,
    collaboration: 0.90,
    latencyAvg: 0.5,
    status: "idle",
    alpha: 8,
    beta: 2,
    meanReward: 0.87,
    uncertainty: 0.08,
    runs: 20,
    wins: 17,
    losses: 2,
    elo: 1490,
    ucbScore: 0,
    graphTrust: 0.78,
    bayesianMean: 0.80,
  }),
];

export const TASKS = [
  {
    id: "market_research",
    type: "market_research",
    description: "Research the target market, size, and competitors",
    requiredSkills: ["research", "market_analysis"],
    status: "pending" as const,
  },
  {
    id: "positioning",
    type: "positioning",
    description: "Define product positioning and differentiation",
    requiredSkills: ["product_design", "positioning"],
    status: "pending" as const,
  },
  {
    id: "landing_page_copy",
    type: "landing_page_copy",
    description: "Write compelling landing page headline and copy",
    requiredSkills: ["copywriting", "landing_page"],
    status: "pending" as const,
  },
  {
    id: "pitch_script",
    type: "pitch_script",
    description: "Draft a 90-second pitch script",
    requiredSkills: ["pitch", "narrative"],
    status: "pending" as const,
  },
  {
    id: "risk_review",
    type: "risk_review",
    description: "Identify key risks and mitigation strategies",
    requiredSkills: ["risk_analysis", "critical_thinking"],
    status: "pending" as const,
  },
  {
    id: "final_eval",
    type: "final_eval",
    description: "Evaluate all outputs and produce final score",
    requiredSkills: ["evaluation", "scoring"],
    status: "pending" as const,
  },
];
