import { Agent } from "./types";
import { AGENT_PROVIDER } from "./providers-config";

const withProvider = (agent: Omit<Agent, "provider">): Agent => ({
  ...agent,
  provider: AGENT_PROVIDER[agent.id] ?? "gemini",
});

export const DEFAULT_AGENTS: Agent[] = [
  withProvider({
    id: "planner",
    name: "PlannerAgent",
    role: "Decomposes missions into structured subtask graphs",
    skills: ["planning", "decomposition", "strategy", "coordination"],
    price: 0.04,
    reputation: 88,
    factuality: 0.88,
    usefulness: 0.92,
    collaboration: 0.90,
    latencyAvg: 1.2,
    status: "idle",
    alpha: 8,
    beta: 2,
    meanReward: 0.82,
    uncertainty: 0.09,
    runs: 12,
    wins: 9,
    losses: 2,
    elo: 1480,
    ucbScore: 0,
    graphTrust: 0.75,
    bayesianMean: 0.8,
  }),
  withProvider({
    id: "research",
    name: "ResearchAgent",
    role: "Conducts market research and competitive analysis",
    skills: ["research", "market_analysis", "data_synthesis", "competitive_intel"],
    price: 0.06,
    reputation: 78,
    factuality: 0.72,
    usefulness: 0.80,
    collaboration: 0.70,
    latencyAvg: 2.1,
    status: "idle",
    alpha: 5,
    beta: 4,
    meanReward: 0.64,
    uncertainty: 0.15,
    runs: 8,
    wins: 5,
    losses: 3,
    elo: 1420,
    ucbScore: 0,
    graphTrust: 0.55,
    bayesianMean: 0.56,
  }),
  withProvider({
    id: "source_verifier",
    name: "SourceVerifierAgent",
    role: "Verifies claims and validates sources for factual accuracy",
    skills: ["fact_checking", "source_verification", "accuracy", "research"],
    price: 0.05,
    reputation: 91,
    factuality: 0.94,
    usefulness: 0.87,
    collaboration: 0.88,
    latencyAvg: 1.5,
    status: "idle",
    alpha: 9,
    beta: 2,
    meanReward: 0.89,
    uncertainty: 0.07,
    runs: 15,
    wins: 13,
    losses: 1,
    elo: 1510,
    ucbScore: 0,
    graphTrust: 0.88,
    bayesianMean: 0.82,
  }),
  withProvider({
    id: "builder",
    name: "BuilderAgent",
    role: "Synthesizes research into actionable product specs",
    skills: ["product_design", "synthesis", "go_to_market", "positioning"],
    price: 0.07,
    reputation: 80,
    factuality: 0.82,
    usefulness: 0.88,
    collaboration: 0.82,
    latencyAvg: 1.8,
    status: "idle",
    alpha: 7,
    beta: 3,
    meanReward: 0.75,
    uncertainty: 0.11,
    runs: 10,
    wins: 7,
    losses: 2,
    elo: 1450,
    ucbScore: 0,
    graphTrust: 0.68,
    bayesianMean: 0.70,
  }),
  withProvider({
    id: "pitch",
    name: "PitchAgent",
    role: "Crafts compelling narratives and pitch scripts",
    skills: ["copywriting", "pitch", "narrative", "landing_page"],
    price: 0.05,
    reputation: 86,
    factuality: 0.80,
    usefulness: 0.91,
    collaboration: 0.85,
    latencyAvg: 1.4,
    status: "idle",
    alpha: 8,
    beta: 2,
    meanReward: 0.83,
    uncertainty: 0.09,
    runs: 11,
    wins: 9,
    losses: 1,
    elo: 1460,
    ucbScore: 0,
    graphTrust: 0.72,
    bayesianMean: 0.80,
  }),
  withProvider({
    id: "skeptic",
    name: "SkepticAgent",
    role: "Challenges assumptions and surfaces critical risks",
    skills: ["risk_analysis", "critical_thinking", "red_teaming", "fact_checking"],
    price: 0.04,
    reputation: 93,
    factuality: 0.91,
    usefulness: 0.89,
    collaboration: 0.84,
    latencyAvg: 1.1,
    status: "idle",
    alpha: 9,
    beta: 1,
    meanReward: 0.91,
    uncertainty: 0.06,
    runs: 14,
    wins: 13,
    losses: 0,
    elo: 1540,
    ucbScore: 0,
    graphTrust: 0.82,
    bayesianMean: 0.90,
  }),
  withProvider({
    id: "evaluator",
    name: "EvaluatorAgent",
    role: "Scores agent outputs on quality, factuality, and usefulness",
    skills: ["evaluation", "scoring", "quality_assurance", "feedback"],
    price: 0.03,
    reputation: 90,
    factuality: 0.93,
    usefulness: 0.90,
    collaboration: 0.88,
    latencyAvg: 1.0,
    status: "idle",
    alpha: 9,
    beta: 2,
    meanReward: 0.88,
    uncertainty: 0.07,
    runs: 18,
    wins: 16,
    losses: 1,
    elo: 1500,
    ucbScore: 0,
    graphTrust: 0.80,
    bayesianMean: 0.82,
  }),
  withProvider({
    id: "market_maker",
    name: "MarketMakerAgent",
    role: "Orchestrates auctions and selects optimal agent swarms",
    skills: ["routing", "optimization", "orchestration", "auction"],
    price: 0.02,
    reputation: 92,
    factuality: 0.90,
    usefulness: 0.94,
    collaboration: 0.92,
    latencyAvg: 0.8,
    status: "idle",
    alpha: 9,
    beta: 2,
    meanReward: 0.90,
    uncertainty: 0.07,
    runs: 20,
    wins: 18,
    losses: 1,
    elo: 1520,
    ucbScore: 0,
    graphTrust: 0.85,
    bayesianMean: 0.82,
  }),
  withProvider({
    id: "reputation",
    name: "ReputationAgent",
    role: "Updates agent reputation scores after each mission",
    skills: ["reputation", "memory", "scoring", "feedback"],
    price: 0.01,
    reputation: 89,
    factuality: 0.92,
    usefulness: 0.88,
    collaboration: 0.90,
    latencyAvg: 0.5,
    status: "idle",
    alpha: 8,
    beta: 2,
    meanReward: 0.87,
    uncertainty: 0.08,
    runs: 20,
    wins: 17,
    losses: 2,
    elo: 1490,
    ucbScore: 0,
    graphTrust: 0.78,
    bayesianMean: 0.80,
  }),
];

export const TASKS = [
  {
    id: "market_research",
    type: "market_research",
    description: "Research the target market, size, and competitors",
    requiredSkills: ["research", "market_analysis"],
    status: "pending" as const,
  },
  {
    id: "positioning",
    type: "positioning",
    description: "Define product positioning and differentiation",
    requiredSkills: ["product_design", "positioning"],
    status: "pending" as const,
  },
  {
    id: "landing_page_copy",
    type: "landing_page_copy",
    description: "Write compelling landing page headline and copy",
    requiredSkills: ["copywriting", "landing_page"],
    status: "pending" as const,
  },
  {
    id: "pitch_script",
    type: "pitch_script",
    description: "Draft a 90-second pitch script",
    requiredSkills: ["pitch", "narrative"],
    status: "pending" as const,
  },
  {
    id: "risk_review",
    type: "risk_review",
    description: "Identify key risks and mitigation strategies",
    requiredSkills: ["risk_analysis", "critical_thinking"],
    status: "pending" as const,
  },
  {
    id: "final_eval",
    type: "final_eval",
    description: "Evaluate all outputs and produce final score",
    requiredSkills: ["evaluation", "scoring"],
    status: "pending" as const,
  },
];
